FROM continuumio/miniconda3:4.12.0

WORKDIR /usr/src/app

COPY environment.yml .

RUN conda env create -f environment.yml

ENV PATH="/opt/conda/envs/ctorch/bin/:${PATH}"
ENV CONDA_DEFAULT_ENV ctorch
ENV CONDA_PREFIX /opt/conda/env/ctorch

EXPOSE 8800