name: ctorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python==3.9.13
  - boto3==1.24.75
  - pandas==1.4.4
  - scikit-learn==1.1.2
  - scikit-image==0.19.3
  - pytorch==1.12.1
  - torchvision==0.13.0
  - torchaudio==0.12.1
  - cudatoolkit==11.3.1
  # Interactive
  - jupyter==1.0.0
  - matplotlib==3.5.3
  - seaborn==0.12.0
  # Testing
  - pycodestyle==2.9.1
  - pytest==7.1.3
  - pytest-cov==3.0.0
  - pytest-pycodestyle==2.2.0
  # Pip
  - pip==22.2.2